-d C:\github\Sem3-OOP-Csharp\electronica\Laba3\code\impl\gwsynthesis\Lab_3.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\github\Sem3-OOP-Csharp\electronica\Laba3\code\src\Lab_3.cst
-cfg C:\github\Sem3-OOP-Csharp\electronica\Laba3\code\impl\pnr\device.cfg
-sdc C:\github\Sem3-OOP-Csharp\electronica\Laba3\code\src\Lab_3.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
